version: "2"
services:
  web:
    build: .
    labels:
      - convox.port.443.protocol=tls
      - convox.port.443.proxy=true
    ports:
      - 80:4000
      - 443:4001
    links:
      - database
    environment:
      - PAID_APP_ID
      - PAID_SECRET

  database:
    image: convox/postgres
    ports:
      - 5432
    volumes:
      - /var/lib/postgresql/data

