version: "2"
services:
  database:
    image: convox/postgres
    ports:
    - 5432/tcp
    volumes:
    - /var/lib/postgresql/data
  web:
    build:
      context: .
    command: bin/rails server -p $$PORT -e $$RAILS_ENV -b 0.0.0.0
    environment:
    - PAID_APP_ID
    - PAID_SECRET
    - PORT=4001
    - RAILS_LOG_TO_STDOUT=enabled
    - LANG=en_US.UTF-8
    - RAILS_ENV=production
    - RACK_ENV=production
    - SECRET_KEY_BASE=bb51f4c214fc56dd24509502d85fc5fcac2f3fd800e80de95b49076e3eac976c26216cbf4a2a9c6f05536dc2d3ae7ca7ec8fc0d4b201dc4e9f23138d43963432
    - RAILS_SERVE_STATIC_FILES=enabled
    links:
    - database
    ports:
    - 80:4001/tcp
    - 443:4001/tcp
