# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51154e43a9506c3f98b359b3b444aa0f63e01d240de4914c7bd6bcf374bd8790ef6b5a55a1f536c6fe46cd05a7ac244ecf9d01480bc0c54b0f68bab623840055
  paid_app_id: <%= ENV['PAID_APP_ID'] %>
  paid_secret: <%= ENV['PAID_SECRET'] %>

test:
  secret_key_base: 439c78ef305c4b42ca4be63eac42c3c652adcb0e1c002c1d1486660a4dcf73220b810a2cc38056d4f160f30a2d25b252adb5bb940e016a68336ce83e02be2ccb
  paid_app_id: <%= ENV['PAID_APP_ID'] %>
  paid_secret: <%= ENV['PAID_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  paid_app_id: <%= ENV['PAID_APP_ID'] %>
  paid_secret: <%= ENV['PAID_SECRET'] %>
